### ISSUE TITLE
website (bad link)

### ISSUE THREAD

**Issue by askeblad** [haskell/alex#204]
https://www.haskell.org/alex/

hyperlink on cabal-install should be https://wiki.haskell.org/Cabal-Install

**Comment by askeblad** [comment]
https://github.com/vaerksted/vaerksted.github.io

A temporary location of a validated update.

No attempt was made to update the links or textual content.

**Comment by andreasabel** [comment]
Thanks @askeblad, for the alert!

Actually, I do not know where the source code of the page https://www.haskell.org/alex/ resides.  
- I have not found it in this repository.  
- No further hints at https://github.com/haskell-infra/www.haskell.org/#details-alex

Who knows about this? @simonmar ? @Ericson2314 ?

**Comment by askeblad** [comment]
github.com/haskell/haskell.github.io

with alex and happy source code on GitHub their webpages could be relocated to a newly created repo as above

**Comment by andreasabel** [comment]
> github.com/haskell/haskell.github.io

This webpage does not exist, @askeblad.  Which one did you mean?

**Comment by askeblad** [comment]
If the proposed new repo is created please do not require two-factor authentication on invitations soliciting new members.

**Comment by askeblad** [comment]
The original idea for the new repo is found in `haskell-infra/www.haskell.org` issue #181.

I don't herein link to that issue as is is not pertinent to this current ticket.

**Comment by andreasabel** [comment]
I'd like to understand first how the current setup works, so I reported upstream:
- https://github.com/haskell-infra/www.haskell.org/issues/183

**Comment by askeblad** [comment]
> source/mechanics of the alex and happy subsites

[alex](https://www.haskell.org/alex/) and [happy](https://www.haskell.org/happy/)

right clicking on the above webpages and from the appearing context menus clicking to View Page Source in new browser tabs

mostly the same structure could be retained (were the source copied to proposed new repo `haskell/haskell.github.io`)

_e.g._, from the alex webpage

`doc/html/index.html`

and from the foregoing file

`doc/html/fptools.css`

**Comment by askeblad** [comment]
@andreasabel 

https://github.com/vaerksted/vaerksted.github.io

links updated

https://vaerksted.github.io/alex.html

according to the **Maintainer** discretion

```diff
- <p><a href="http://www.haskell.org/~simonmar"><i>Simon Marlow</i></a> <a href="mailto:simonmar@microsoft.com">
+ <p><a href="https://simonmar.github.io/"><i>Simon Marlow</i></a> <a href="mailto:marlowsd@gmail.com">
```
you can use if you now have write authority to `haskell.org`

**Comment by askeblad** [comment]
closed due to age

**Comment by andreasabel** [comment]
Thanks for your efforts, @askeblad.  I got now access to the Alex homepage and will fix it.  Ctd at #128.
