### ISSUE TITLE
Makefile (examples)

### ISSUE THREAD

**Issue by askeblad** [haskell/alex#209]
With alex-3.2.7 examples/Makefile wasn't updated.

`ALEX_OPTS = --template=.. -g`

The data/AlexWrapper-gscan file no longer exists.

**Comment by andreasabel** [comment]
Seems like `examples/Makefile` is broken:
```
alex-3.2.7.1/examples[master x]$ make all
../dist/build/alex/alex --template=.. -g lit.x -o lit.alex.hs
make: ../dist/build/alex/alex: Command not found
make: *** [Makefile:19: lit.alex.hs] Error 127
```
It relies on `v1-cabal` layout of the `dist` folder.

**Comment by askeblad** [comment]
presume **Won't Fix**  here

closing
