### ISSUE TITLE
Make `haskell.org/alex` redirect to `haskell-alex.readthedocs.io` ?

### ISSUE THREAD

**Issue by andreasabel** [haskell/alex#215]
I have updated https://haskell.org/alex (fixing #128), but I wonder whether we should simply make it a redirect to https://haskell-alex.readthedocs.io and maintain all information there?

- [x] @gbaz, can https://haskell.org/alex be simply made a redirect (and how)?
- [x] There is currently old stuff at `webhost.haskell.org:alex` that should be deleted:
  ```
  sftp> ls
  _darcs                    alex-2.1.0rc.tar.gz       dist                      doc                       
  index.html                index.html-darcs-backup0  
  ```
  After #128, only `index.html` is used, the rest is not connected (and badly outdated).
  [`dist` contains some old packings of alex-2, and `doc` the old rendered docbook manual.]
  I am going to delete all of this, unless some screams.

**Comment by tomjaguarpaw** [comment]
The Haddock maintainers [chose to host their documentation on readthedocs](https://github.com/haskell/haddock/issues/1443). If you want to do the same then @gbaz or another member of the [haskell-infra team](https://github.com/haskell-infra/haskell-admins#the-team-and-how-to-contact-them) can set up a redirect for you.

On the other hand, you are welcome to just integrate the page into the [www.haskell.org repo](https://github.com/haskell-infra/www.haskell.org/).

**Comment by andreasabel** [comment]
> On the other hand, you are welcome to just integrate the page into the [www.haskell.org repo](https://github.com/haskell-infra/www.haskell.org/).

How would that work?  Would it be a `.markdown` file under `site/`?  Or where would I put the `.html` file (for the simplest solution)?

**Comment by tomjaguarpaw** [comment]
> Would it be a .markdown file under site/?

That would work, and I *think* you can also put the HTML contents into the `.markdown` file because Markdown should allow embedding of HTML.

**Comment by askeblad** [comment]
isn't Markdown problematic with colour use

**Comment by Ericson2314** [comment]
The docs are update, and we are ready to do this.

**Comment by Ericson2314** [comment]
This is done!
