### ISSUE TITLE
Deriving Ord for AlexPosn

### ISSUE THREAD

**Issue by Kleidukos** [haskell/alex#233]
I'm trying to use Alex with Megaparsec, whose [Stream](https://hackage.haskell.org/package/megaparsec-9.3.0/docs/Text-Megaparsec-Stream.html#t:Stream) typeclass requires an Ord constraint on the elements of a list or sequence of tokens.

As I pre-lex my source input with Alex and turn it into a Seq of Ranged Tokens making use of AlexPosn for the position, it is the last thing that does not have an Ord instance.

I can provide a patch.

**Comment by Kleidukos** [comment]
@andreasabel @Ericson2314 Any opinion on this? :)

**Comment by andreasabel** [comment]
@Kleidukos An `Ord` instances for `AlexPosn` is welcome.  https://github.com/haskell/alex/blob/81aff838d75be6fedbe06998c3d283529b9a4a9f/src/ParseMonad.hs#LL66C1-L66C1
The type itself is non-free: the second and third fields (line and column) are determined by the first field (character position).
I think the derived  (lexicographic) `Ord` instance would work nevertheless.
Which implementation did you have in mind?

**Comment by Kleidukos** [comment]
Yes I was really going on with the basic `deriving stock (Ord)` at first.

**Comment by andreasabel** [comment]
This will be a minor version bump (even though Alex does not have to follow the PVP): add non-orphan instance.
