### ISSUE TITLE
upgrading problems with Cabal

### ISSUE THREAD

**Issue by rw111** [haskell/alex#245]
The following command line conversation with Cabal shows that I can't use it to upgrade Alex. I don't use Haskell very often and need it only to install other software for which Alex is a dependency, so apologies if I have missed something that is obvious. As I see it it just doesn't succeed in upgrading Alex.

robert@robert-HP:~$ cabal --version
cabal-install version 3.10.1.0
compiled using version 3.10.1.0 of the Cabal library 

robert@robert-HP:~$ cabal info alex
* alex             (program)
    Synopsis:      Alex is a tool for generating lexical analysers in Haskell
    Versions available: 2.2, 2.3.3, 2.3.4, 2.3.5, 3.1.7, 3.2.5, 3.2.6, 3.3.0.0,
                        3.4.0.0 (and 27 others)
    Versions installed: [ Unknown ]
    Homepage:      http://www.haskell.org/alex/
    Bug reports:   https://github.com/haskell/alex/issues
    Description:   Alex is a tool for generating lexical analysers in Haskell.
                   It takes a description of tokens based on regular expressions
                   and generates a Haskell module containing code for scanning
                   text efficiently. It is similar to the tool lex or flex for
                   C/C++.
    Category:      Development
    License:       BSD3
    Author:        Chris Dornan and Simon Marlow
    Maintainer:    https://github.com/haskell/alex
    Source repo:   https://github.com/haskell/alex.git
    Executables:   alex
    Dependencies:  base >=2.1 && <5, array, containers, directory, base, process
    Cached:        Yes

robert@robert-HP:~$ alex --version
Alex version 3.2.5, (c) 2003 Chris Dornan and Simon Marlow

robert@robert-HP:~$ cabal install alex-3.4.0.0 --overwrite-policy=always
Resolving dependencies...
Symlinking 'alex' to '/home/robert/.cabal/bin/alex'

robert@robert-HP:~$ alex --version
Alex version 3.2.5, (c) 2003 Chris Dornan and Simon Marlow

**Comment by andreasabel** [comment]
This looks like a PATH problem.  Have you tried `which alex`? 
You need `~/.cabal/bin` in your PATH _before_ the entry that supplies the ghc-shipped alex.

**Comment by rw111** [comment]
Yes, that was it. Thanks.

**Comment by andreasabel** [comment]
Great!
