### ISSUE TITLE
Workflow `emulated` is failing

### ISSUE THREAD

**Issue by andreasabel** [haskell/alex#263]
https://github.com/haskell/alex/actions/runs/12539105106/job/34974731660#step:3:71
> ERROR: failed to solve: ppc64le/ubuntu:rolling: failed to resolve source metadata for docker.io/ppc64le/ubuntu:rolling: no match for platform in manifest: not found

ATTN @sgraf812

**Comment by sgraf812** [comment]
I see you found a fix. Thanks!
